### ISSUE TITLE
IndexError in a["entries"][0]["media$content"][0]["plfile$downloadUrl"]

### ISSUE THREAD

**Issue by brianjmurrell** [learningit/plugin.video.cbc#1] opened 2015-04-17 12:59 UTC
Hi,

I am using your plugin -- great work BTW -- and I got this error:

```
Traceback (most recent call last):
...
  File "/home/mythtv/.kodi/addons/plugin.video.cbc/default.py", line 212, in getLink
    u = a["entries"][0]["media$content"][0]["plfile$downloadUrl"]
IndexError: list index out of range
```

Presumably it means that the data that is returned in the ```getLink()``` is incomplete or bad in some way.

When this happens, it would be most interesting to see the contents of ```a``` don't you think?

I am not a Kodi [plugin] developer so I'm not sure what the best way to go about doing that.  Perhaps your ```log``` function is the best way.  But I am also not sure the correct way to inform Kodi about the failure rather than the successful case of using ```xbmcplugin.setResolvedUrl```

Something like:

```
try:
    u = a["entries"][0]["media$content"][0]["plfile$downloadUrl"]
except IndexError:
    log("got an index error trying to get a[\"entries\"][0][\"media$content\"][0][\"plfile$downloadUrl\"] out of %s" % a)
    # inform Kodi and get out of here

```

in ```getLink()``` rather than just the:

```
u = a["entries"][0]["media$content"][0]["plfile$downloadUrl"]
```

perhaps?  Sorry about the format above rather than a patch.  I'm not working in a git repo and am just hacking up the live file as I go.

**Comment by learningit** [comment] 2015-04-17 13:15
Thanks. Your approach is correct, but I would like to see the entire log so that I can look into the root cause. Could you post the log to either xbmclogs.com or pastebin.com ? I tend not to wrap statements like this with a try-except unless I know that there is a chance of failure. Doing so masks problems which need to be looked into and there's rarely an elegant and complete way to recover from this type of an error - but that's just kind of a personal choice.

This particular website occasionally suffers from internal errors where it either doesn't return data or the connection times out. I'd really like to see the log so I can figure out what's going on.

**Comment by learningit** [comment] 2015-04-17 14:05
I had a further look at this and I will probably leave it they way it is. A script error will be reported by Kodi when it occurs and the full debug data will be in the log. The script terminates on error so setResolvedUrl will not execute. From the end user perspective, the url failed to play and whether I tell them that it's an index error or Kodi reports a script error is moot. I guess that I could do a notification message that there is "no playable video" which is a bit more elegant. BTW the log function can often cause more problems in and of itself if the data contains weird unicode chars which can't be decoded to utf-8 - so it needs to be used with care as well.

**Comment by brianjmurrell** [comment] 2015-04-17 16:45
> Could you post the log to either xbmclogs.com or pastebin.com ?

I'm not actually using your plugin in Kodi.  :-)  I have another project where my interest is in downloading the episode, not actually watching it streaming.  So I wrote my own tool and stubbed out the xbmc functions.  Apart from this Index Error it seems to work well.

On that topic, I had wondered how receptive you'd be to separating out the website scraping from the XBMC/Kodi presentation so that the website scraping could be used in other projects.  :-)

> I tend not to wrap statements like this with a try-except unless I know that there is a chance of failure.

Right.  But clearly there is in this case.

> Doing so masks problems

It only masks them if you pass on the exception.  If you use the exception to handle the error nothing gets masked and the exceptional situation gets handled.

> which need to be looked into and there's rarely an elegant and complete way to recover from this type of an error - but that's just kind of a personal choice.

At minimum we could log the data that caused the problem such as I did in my example.

> This particular website occasionally suffers from internal errors where it either doesn't return data or the connection times out.

So some retry logic might be necessary.

> I'd really like to see the log so I can figure out what's going on

As above, there is no log per se.

> I had a further look at this and I will probably leave it they way it is.

You are not even interested in why an Index Error can happen here?

> A script error will be reported by Kodi when it occurs and the full debug data will be in the log.

Will the content scraped from the website be in the log in the same was as my patch makes it available?

> The script terminates on error so setResolvedUrl will not execute.

Right, but it leaves Kodi and the user kind of wondering what went wrong.

> From the end user perspective, the url failed to play and whether I tell them that it's an index error or Kodi reports a script error is moot.

Sure, but the important part is logging what the script scraped from the website that caused the error.

**Comment by learningit** [comment] 2015-04-17 17:05
I'm not going to spend a lot of time on this - you're clearly doing things with script for which it wasn't intended. It would be nice if you could tell me what particular choice was giving you an error so I could look into it.

**Closed** 2015-04-17 17:27 UTC

**Comment by brianjmurrell** [comment] 2015-04-17 17:34
Right.  My use wasn't intended, but does work when the data on the website is available/working.

The show I was seeing the failure on was *The National*.

**Comment by learningit** [comment] 2015-04-17 18:06
Which category and episode - there's a couple hundred in there

**Comment by brianjmurrell** [comment] 2015-04-17 18:13
```getShows("/player/Shows/Shows/", "Shows")``` and then out of that list the one whose ```['Title'].startswith("The National - Full Show - ")``` which should yield the most recent full episode.

Like I said, this usually works and even works right now.  It was just the moment I tried last night where it was not.  I tried 4 times a one hour intervals and only one of them failed.  That's why I think the scraped content would be interesting to see when this does happen.

**Comment by learningit** [comment] 2015-04-17 18:25
For a Kodi addon it's not that interesting. The typical user just cares if they can play it or not. If they turn on debug level logging in Kodi, the addon will capture the html request and response which is more useful to look at than just part of the data. Good luck with your project.

**Comment by brianjmurrell** [comment] 2015-04-17 18:28
You never said how receptive you would be to separating out the data gathering from the Kodi integration/presentation.

The idea would be a library (more or less) for doing the scraping where the Kodi plugin calls into the library instead of doing the scraping itself.  That way other (i.e. non-Kodi) consumers can leverage the same code.

**Comment by learningit** [comment] 2015-04-17 18:43
No interest.

**Comment by brianjmurrell** [comment] 2015-04-17 18:51
So you would not even accept a patch that achieved it?

**Comment by learningit** [comment] 2015-04-17 18:53
Looking at your track record, no.

**Comment by brianjmurrell** [comment] 2015-04-17 19:06
What does that mean exactly?  What track record are you referring to?

**Comment by learningit** [comment] 2015-04-17 19:10
Look fork the repo and do whatever you want with it.

**Comment by brianjmurrell** [comment] 2015-04-17 19:20
Sure, I can do that.  But that only helps me.

What I am proposing is expanding the use of your plugin(s) beyond just Kodi to provide a general scraping interface that other projects can use as well.  Of course your own plugin(s) would continue to make use of them.

I am proposing that if the scraping of content were made more generic and interfacable, that you could attract interest in your project(s), get more help expanding and maintaining (as the website content changes -- and we know it will) them making the whole project richer.

But it seems you are not interested in that, which is a pity.  More hands make light work and all that.

**Comment by learningit** [comment] 2015-04-17 22:17
Less than zero interest in supporting downloaders. I purposely choose m3u8 format when and where I can for that reason. You'll notice that the latest YT addon doesn't have a downloader anymore, there's a reason for it. I'm hard pressed to think of a rationale other than piracy which requires downloading.

**Comment by brianjmurrell** [comment] 2015-04-18 00:29
First of all I take serious offence at your accusation of piracy!  My motivation for downloading is absolutely no different than yours is for watching on Kodi or anyone else's.  I merely want to time-shift.  I just prefer to not rely on having Internet access to "stream" while I time-shift.

There is absolutely no difference between streaming and downloading when it's for purposes of time-shifting so you can just get down off of your high horse there and stop slandering innocent people.
